name: WSEI DevOps Project CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Pull repo
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository }}/devops-app:latest .
      - name: Security scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devops-app'
          format: 'table'
          exit-code: 0
          severity: 'CRITICAL,HIGH'
      - name: Test
        run: echo "Test"
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/devops-app:latest
